spring:
  application:
    name: zuul
  cloud: 
    config: 
      override-none: true
  
  
server:
  port: 3001
  
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

# 默认配置，最好自己手动配置
# 自动配置是从eureka获取注册表。根据注册表自动配置
# 如果从eureka获取不到一个服务的注册信息，就无法完成自动配置
zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
    
  retryable: true
  
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  OkToRetryOnAllOperations: false
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream